# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/muxctrl.xdc

# Block Designs: bd/OEXP01_muxctrl/OEXP01_muxctrl.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl || ORIG_REF_NAME==OEXP01_muxctrl} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_MUX2T1_5_0_0/OEXP01_muxctrl_MUX2T1_5_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_MUX2T1_5_0_0 || ORIG_REF_NAME==OEXP01_muxctrl_MUX2T1_5_0_0} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_MUX2T1_5_0_1/OEXP01_muxctrl_MUX2T1_5_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_MUX2T1_5_0_1 || ORIG_REF_NAME==OEXP01_muxctrl_MUX2T1_5_0_1} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_MUX4T1_5_0_1/OEXP01_muxctrl_MUX4T1_5_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_MUX4T1_5_0_1 || ORIG_REF_NAME==OEXP01_muxctrl_MUX4T1_5_0_1} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_xlslice_0_0/OEXP01_muxctrl_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_xlslice_0_0 || ORIG_REF_NAME==OEXP01_muxctrl_xlslice_0_0} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_xlslice_0_1/OEXP01_muxctrl_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_xlslice_0_1 || ORIG_REF_NAME==OEXP01_muxctrl_xlslice_0_1} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_xlconcat_0_0/OEXP01_muxctrl_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_xlconcat_0_0 || ORIG_REF_NAME==OEXP01_muxctrl_xlconcat_0_0} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_xlconcat_0_1/OEXP01_muxctrl_xlconcat_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_xlconcat_0_1 || ORIG_REF_NAME==OEXP01_muxctrl_xlconcat_0_1} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_xlconstant_0_0/OEXP01_muxctrl_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_xlconstant_0_0 || ORIG_REF_NAME==OEXP01_muxctrl_xlconstant_0_0} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_xlconstant_1_0/OEXP01_muxctrl_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_xlconstant_1_0 || ORIG_REF_NAME==OEXP01_muxctrl_xlconstant_1_0} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_xlconstant_1_1/OEXP01_muxctrl_xlconstant_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_xlconstant_1_1 || ORIG_REF_NAME==OEXP01_muxctrl_xlconstant_1_1} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_xlconstant_1_2/OEXP01_muxctrl_xlconstant_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_xlconstant_1_2 || ORIG_REF_NAME==OEXP01_muxctrl_xlconstant_1_2} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_MUX8T1_8_0_0/OEXP01_muxctrl_MUX8T1_8_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_MUX8T1_8_0_0 || ORIG_REF_NAME==OEXP01_muxctrl_MUX8T1_8_0_0} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_xlslice_2_0/OEXP01_muxctrl_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_xlslice_2_0 || ORIG_REF_NAME==OEXP01_muxctrl_xlslice_2_0} -quiet] -quiet

# IP: bd/OEXP01_muxctrl/ip/OEXP01_muxctrl_xlslice_3_0/OEXP01_muxctrl_xlslice_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==OEXP01_muxctrl_xlslice_3_0 || ORIG_REF_NAME==OEXP01_muxctrl_xlslice_3_0} -quiet] -quiet

# XDC: bd/OEXP01_muxctrl/OEXP01_muxctrl_ooc.xdc
