# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/OExp02-IP2SOC/Org-Sword.xdc

# Block Designs: bd/CSSTE/CSSTE.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE || ORIG_REF_NAME==CSSTE} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_SAnti_jitter_0_0/CSSTE_SAnti_jitter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_SAnti_jitter_0_0 || ORIG_REF_NAME==CSSTE_SAnti_jitter_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_0/CSSTE_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_0 || ORIG_REF_NAME==CSSTE_xlslice_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_1/CSSTE_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_1 || ORIG_REF_NAME==CSSTE_xlslice_0_1} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_2/CSSTE_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_2 || ORIG_REF_NAME==CSSTE_xlslice_0_2} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_clk_div_0_0/CSSTE_clk_div_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_clk_div_0_0 || ORIG_REF_NAME==CSSTE_clk_div_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_util_vector_logic_0_0/CSSTE_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_util_vector_logic_0_0 || ORIG_REF_NAME==CSSTE_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_3/CSSTE_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_3 || ORIG_REF_NAME==CSSTE_xlslice_0_3} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_4/CSSTE_xlslice_0_4.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_4 || ORIG_REF_NAME==CSSTE_xlslice_0_4} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_5/CSSTE_xlslice_0_5.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_5 || ORIG_REF_NAME==CSSTE_xlslice_0_5} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlconcat_0_0/CSSTE_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlconcat_0_0 || ORIG_REF_NAME==CSSTE_xlconcat_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_util_vector_logic_1_0/CSSTE_util_vector_logic_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_util_vector_logic_1_0 || ORIG_REF_NAME==CSSTE_util_vector_logic_1_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_dist_mem_gen_0_0/CSSTE_dist_mem_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_dist_mem_gen_0_0 || ORIG_REF_NAME==CSSTE_dist_mem_gen_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_0_6/CSSTE_xlslice_0_6.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_0_6 || ORIG_REF_NAME==CSSTE_xlslice_0_6} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_MIO_BUS_0_0/CSSTE_MIO_BUS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_MIO_BUS_0_0 || ORIG_REF_NAME==CSSTE_MIO_BUS_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_Counter_x_0_0/CSSTE_Counter_x_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_Counter_x_0_0 || ORIG_REF_NAME==CSSTE_Counter_x_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_Multi_8CH32_0_0/CSSTE_Multi_8CH32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_Multi_8CH32_0_0 || ORIG_REF_NAME==CSSTE_Multi_8CH32_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_SSeg7_Dev_0_0/CSSTE_SSeg7_Dev_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_SSeg7_Dev_0_0 || ORIG_REF_NAME==CSSTE_SSeg7_Dev_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_SPIO_0_0/CSSTE_SPIO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_SPIO_0_0 || ORIG_REF_NAME==CSSTE_SPIO_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_VGA_0_0/CSSTE_VGA_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_VGA_0_0 || ORIG_REF_NAME==CSSTE_VGA_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_1_0/CSSTE_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_1_0 || ORIG_REF_NAME==CSSTE_xlslice_1_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_1_1/CSSTE_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_1_1 || ORIG_REF_NAME==CSSTE_xlslice_1_1} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_div20_0/CSSTE_div20_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_div20_0 || ORIG_REF_NAME==CSSTE_div20_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_div25_0/CSSTE_div25_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_div25_0 || ORIG_REF_NAME==CSSTE_div25_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_div25_1/CSSTE_div25_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_div25_1 || ORIG_REF_NAME==CSSTE_div25_1} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlconstant_0_0/CSSTE_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlconstant_0_0 || ORIG_REF_NAME==CSSTE_xlconstant_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_b64_0_0/CSSTE_b64_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_b64_0_0 || ORIG_REF_NAME==CSSTE_b64_0_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlconcat_1_0/CSSTE_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlconcat_1_0 || ORIG_REF_NAME==CSSTE_xlconcat_1_0} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_xlslice_1_2/CSSTE_xlslice_1_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_xlslice_1_2 || ORIG_REF_NAME==CSSTE_xlslice_1_2} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_dist_mem_gen_0_1/CSSTE_dist_mem_gen_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_dist_mem_gen_0_1 || ORIG_REF_NAME==CSSTE_dist_mem_gen_0_1} -quiet] -quiet

# IP: bd/CSSTE/ip/CSSTE_IP2CPU_0_0/CSSTE_IP2CPU_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==CSSTE_IP2CPU_0_0 || ORIG_REF_NAME==CSSTE_IP2CPU_0_0} -quiet] -quiet

# XDC: bd/CSSTE/ip/CSSTE_dist_mem_gen_0_0/CSSTE_dist_mem_gen_0_0_ooc.xdc

# XDC: bd/CSSTE/ip/CSSTE_dist_mem_gen_0_1/CSSTE_dist_mem_gen_0_1_ooc.xdc

# XDC: bd/CSSTE/CSSTE_ooc.xdc
