# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/DataPath/DataPath.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath || ORIG_REF_NAME==DataPath} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_xlconstant_0_0/DataPath_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_xlconstant_0_0 || ORIG_REF_NAME==DataPath_xlconstant_0_0} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_ImmGen_0_0/DataPath_ImmGen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_ImmGen_0_0 || ORIG_REF_NAME==DataPath_ImmGen_0_0} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_util_vector_logic_0_0/DataPath_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_util_vector_logic_0_0 || ORIG_REF_NAME==DataPath_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_add_32_0_0/DataPath_add_32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_add_32_0_0 || ORIG_REF_NAME==DataPath_add_32_0_0} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_add_32_0_1/DataPath_add_32_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_add_32_0_1 || ORIG_REF_NAME==DataPath_add_32_0_1} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_MUX2T1_32_0_0/DataPath_MUX2T1_32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_MUX2T1_32_0_0 || ORIG_REF_NAME==DataPath_MUX2T1_32_0_0} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_MUX4T1_32_0_0/DataPath_MUX4T1_32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_MUX4T1_32_0_0 || ORIG_REF_NAME==DataPath_MUX4T1_32_0_0} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_xlslice_0_0/DataPath_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_xlslice_0_0 || ORIG_REF_NAME==DataPath_xlslice_0_0} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_xlslice_0_1/DataPath_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_xlslice_0_1 || ORIG_REF_NAME==DataPath_xlslice_0_1} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_xlslice_0_2/DataPath_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_xlslice_0_2 || ORIG_REF_NAME==DataPath_xlslice_0_2} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_MUX2T1_32_1_0/DataPath_MUX2T1_32_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_MUX2T1_32_1_0 || ORIG_REF_NAME==DataPath_MUX2T1_32_1_0} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_MUX2T1_32_1_1/DataPath_MUX2T1_32_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_MUX2T1_32_1_1 || ORIG_REF_NAME==DataPath_MUX2T1_32_1_1} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_regs_0_0/DataPath_regs_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_regs_0_0 || ORIG_REF_NAME==DataPath_regs_0_0} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_xlconstant_0_1/DataPath_xlconstant_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_xlconstant_0_1 || ORIG_REF_NAME==DataPath_xlconstant_0_1} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_REG32_0_0/DataPath_REG32_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_REG32_0_0 || ORIG_REF_NAME==DataPath_REG32_0_0} -quiet] -quiet

# IP: bd/DataPath/ip/DataPath_ALU_wrapper_0_0/DataPath_ALU_wrapper_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==DataPath_ALU_wrapper_0_0 || ORIG_REF_NAME==DataPath_ALU_wrapper_0_0} -quiet] -quiet

# XDC: bd/DataPath/ip/DataPath_ALU_wrapper_0_0/src/ALU_ooc.xdc

# XDC: bd/DataPath/DataPath_ooc.xdc
