# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/Tag_ram1/Tag_ram1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tag_ram1 || ORIG_REF_NAME==Tag_ram1} -quiet] -quiet

# IP: ip/Tag_ram0/Tag_ram0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Tag_ram0 || ORIG_REF_NAME==Tag_ram0} -quiet] -quiet

# IP: ip/Data_ram1/Data_ram1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Data_ram1 || ORIG_REF_NAME==Data_ram1} -quiet] -quiet

# IP: ip/Data_ram0/Data_ram0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==Data_ram0 || ORIG_REF_NAME==Data_ram0} -quiet] -quiet

# XDC: d:/ISE/2020/OExp06-Cache/cache/cache.gen/sources_1/ip/Tag_ram1/Tag_ram1_ooc.xdc

# XDC: d:/ISE/2020/OExp06-Cache/cache/cache.gen/sources_1/ip/Tag_ram0/Tag_ram0_ooc.xdc

# XDC: d:/ISE/2020/OExp06-Cache/cache/cache.gen/sources_1/ip/Data_ram1/Data_ram1_ooc.xdc

# XDC: d:/ISE/2020/OExp06-Cache/cache/cache.gen/sources_1/ip/Data_ram0/Data_ram0_ooc.xdc
